CREATE DATABASE HOTEL_MANAGMENT_SYSTEM;
USE HOTEL_MANAGMENT_SYSTEM;

/* --------     HOTELS     ----------*/

CREATE TABLE HOTELS (
    Hotel_ID VARCHAR(15),
	HOTEL_NAME VARCHAR(255) NOT NULL,
	HOTEL_LOCATION VARCHAR(255) NOT NULL,
	HOTEL_RATING FLOAT,
	CONSTRAINT PK_HOTEL_ID PRIMARY KEY(Hotel_ID),
	CONSTRAINT HOTEL_RATING_LESS_FIVE CHECK (HOTEL_RATING IS NULL OR HOTEL_RATING <= 5)
);

ALTER TABLE HOTELS
ADD CONSTRAINT UNIQUE_Hotel_NAME_HOTEL_LOCATION UNIQUE (Hotel_NAME, HOTEL_LOCATION);




/* --------     ROOM     ----------*/

CREATE TABLE ROOM(
    ROOM_ID VARCHAR(15),
    HOTEL_ID VARCHAR(15),
    ROOM_TYPE VARCHAR(10) NOT NULL,
    PRICE_$ FLOAT NOT NULL, 
    CAPACITY INT NOT NULL,
    CONSTRAINT PK_ROOM_ID PRIMARY KEY(ROOM_ID),
	CONSTRAINT FK_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(Hotel_ID),
    CONSTRAINT ROOM_PRICE_0_TO_1000 CHECK (PRICE_$ IS NULL OR PRICE_$ <= 1000)
);


/* --------     CUSTOMER     ----------*/

CREATE TABLE CUSTOMER(
Customer_ID VARCHAR(15),
First_Name VARCHAR(15) NOT NULL,
Last_Name VARCHAR(15) NOT NULL,
EMAIL VARCHAR(255),
Phone INT NOT NULL,

CONSTRAINT PK_Customer_ID PRIMARY KEY(Customer_ID)
);

Alter table CUSTOMER ALTER COLUMN Phone BigINT;



/* --------     RESERVATION     ----------*/

CREATE TABLE RESERVATION(
    Reservation_ID VARCHAR(15),
    Hotel_ID VARCHAR(15),
    Room_ID VARCHAR(15),
    Customer_ID VARCHAR(15),
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL,

    CONSTRAINT PK_Reservation_ID PRIMARY KEY(Reservation_ID),
    CONSTRAINT FK_Resv_Hotel_ID FOREIGN KEY (Hotel_ID) REFERENCES HOTELS(Hotel_ID),
    CONSTRAINT FK_Room_ID FOREIGN KEY (Room_ID) REFERENCES ROOM(ROOM_ID),
    CONSTRAINT FK_Customer_ID FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID)
);




/* --------     AMENITY     ----------*/
CREATE TABLE AMENITY(
AMENITY_ID VARCHAR(15),
AMENITY_NAME VARCHAR(20),
CONSTRAINT PK_AMENITY_ID PRIMARY KEY(AMENITY_ID));



/* --------     HOTEL_AMENITY     ----------*/

CREATE TABLE HOTEL_AMENITY(
AMENITY_ID VARCHAR(15),
Hotel_ID VARCHAR(15),
CONSTRAINT FK_AMENITY_ID FOREIGN KEY (AMENITY_ID) REFERENCES AMENITY(AMENITY_ID),
CONSTRAINT FK_AMENITY_HOTEL_ID FOREIGN KEY (Hotel_ID) REFERENCES HOTELS(Hotel_ID),


);


/* --------     TABLES DONE     ----------*/
